# name = input("What is your name?")
# age = input("How old are you?")
# country = input("Where are you from?")
# film = input ("What is your favorite film?")
# print("His name is", name,",", "He is", age,",", "He is from", country,",", "His favorite film it is", film,"." )
